/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as notReallyACrossChainTokenSol from "./NotReallyACrossChainToken.sol";
export type { notReallyACrossChainTokenSol };
