/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXcm,
  IXcmInterface,
} from "../../../contracts/NotReallyACrossChainToken.sol/IXcm";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "uint64",
            name: "refTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "proofSize",
            type: "uint64",
          },
        ],
        internalType: "struct IXcm.Weight",
        name: "weight",
        type: "tuple",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "destination",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "weighMessage",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "refTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "proofSize",
            type: "uint64",
          },
        ],
        internalType: "struct IXcm.Weight",
        name: "weight",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IXcm__factory {
  static readonly abi = _abi;
  static createInterface(): IXcmInterface {
    return new Interface(_abi) as IXcmInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IXcm {
    return new Contract(address, _abi, runner) as unknown as IXcm;
  }
}
